### ISSUE TITLE
How to define a nested array(multidimensional array) with Double type? 

### ISSUE THREAD

**Issue by neil-wu** [PonyCui/PPJSONSerialization#4]
In my project,I need to define a multidimensional array, like this: 

```
let jsonstr: String = "{ \"Type\": \"Polygon\", \"ValueList\": [ [30.2],[10.5] ] }"

class AreaArrayObj: PPJSONSerialization {
    var Type: String = ""
    var ValueList: [ [Double] ] = [[0.0]]
}
```

It seems that the ValueList is always empty array.

`tplObject.copy() as? PPJSONSerialization` is nil

**Comment by PonyCui** [comment]
It's really a problem, I will fix it ASAP.

**Comment by neil-wu** [comment]
thx.

**Comment by neil-wu** [comment]
I make a temporary modifications [here](https://github.com/neil-wu/PPJSONSerialization/commit/1da6101505c7fece697225b913e0120603db3e4f)

**Comment by PonyCui** [comment]
Dear neil-wu, I recode and push to master now.
Now support multiple dimension array (more than 10 dimension is also availabel).

**Comment by neil-wu** [comment]
well done. 
thx

**Comment by neil-wu** [comment]
One more thing, the json Object value may be null. If it is null, `assertionFailure("Root must be Dictionary")` will fail.
Test case: 

```
let jsonstr: String = "{ \"Type\": \"Polygon\", \"ValueList\": [ [30.2],[10.5] ], \"error\": null  }"
```

```
class ErrorObj: PPJSONSerialization {
    var Code: Int = 0
}
class AreaArrayObj: PPJSONSerialization {
    var Type: String = ""
    var ValueList: [ [Double] ] = [[0.0]]
    var error: ErrorObj = ErrorObj()
}
```

**Comment by PonyCui** [comment]
remove the assert, it's ok.

**Comment by PonyCui** [comment]
And make a pull request.

**Comment by neil-wu** [comment]
:) OK
